### ISSUE TITLE
Pdfpage.target_of_pagenumber not in documentation

### ISSUE THREAD

**Issue by waclena** [johnwhitington/camlpdf#16]
I discovered the function I desperately needed (Pdfpage.target_of_pagenumber) by looking through the source code, but it's not in the [documentation](http://www.coherentpdf.com/camlpdf).

Is this a mistake, or is the function deprecated or not to be used?  If the latter, how would I implement an equivalent?

(Thanks a million for camlpdf -- I've used it in several projects at the University of Chicago Library!)

**Comment by johnwhitington** [comment]
I don't think we want to expose `target_of_pagenumber` directly, since it's fairly easy to recreate once you have `Pdfpage.page_object_number`, and it's not clear that its lack of error-reporting on finding no page object number is a good API.

So I suggest exposing `Pdfpage.page_object_number` in `pdfpage.mli` and copying `Pdfpage.target_of_pagenumber` into your code. Add something like this to `pdfpage.mli` (untested):

```
val page_object_number : Pdf.t -> int -> int option
```

**Comment by waclena** [comment]
John Whitington <notifications@github.com> writes:

> I don't think we want to expose `target_of_pagenumber` directly, since
> it's fairly easy to recreate once you have
> `Pdfpage.page_object_number`, and it's not clear that its lack of
> error-reporting on finding no page object number is a good API.
>
> So I suggest exposing `Pdfpage.page_object_number` in `pdfpage.mli`
> and copying `Pdfpage.target_of_pagenumber` into your code. Add
> something like this to `pdfpage.mli` (untested):
>
> ```
> val page_object_number : Pdf.t -> int -> int option
> ```

I did that in my camlpdf repo, pinned it with opam, and it works
great:

    (** Find a page indirect from the page tree of a document, given a page number. *)
    val page_object_number : Pdf.t -> int -> int option

I also copied Pdfpage.target_of_pagenumber into my code as you
recommended and that's working too.  Thanks!

Right now I need Pdfannot.add_annotation; I'm trying to figure out how
to implement it, and if I get it to work, I'll pass it on.
