### ISSUE TITLE
Opam installation failing

### ISSUE THREAD

**Issue by ttamttam** [johnwhitington/camlpdf#22]
Hello,

I can't install camlpdf package with opam, unless I pin to the development repository instead of the 2.2.1 release.

A new release and opam adaptation would help solving this?

Sincerely

**Comment by johnwhitington** [comment]
I suspect this has to do with the change in 4.06 whereby -unsafe-string is no longer the default and must be explicitly given as a flag.

I think the best way is to use OPAM's patching mechanism, perhaps? Is there a way to say a patch is only required > 4.06.0?

**Comment by ttamttam** [comment]
Yes, you are right: this is due to the `-unsafe-string` change.
I'll have a look at what can be done with a filtered patch  (>= 4.06) and come back here.

**Comment by ttamttam** [comment]
I tried this: https://github.com/ocaml/opam-repository/pull/11844
