### ISSUE TITLE
Port building system to Dune

### ISSUE THREAD

**Issue by XVilka** [johnwhitington/camlpdf#28]
[Dune](https://dune.build) is now the most common modern way of building OCaml programs and libraries, and aims to be the only(?) one. It also simplify greatly mundane tasks like dependency management, release process, etc.

**Comment by johnwhitington** [comment]
The commercial tools for which `camlpdf` was written need to have no dependencies other than C and make, so they can be used on all systems, including obscure ones such as AIX and HP/UX.

If you want to provide an alternative Dune build script, I am happy to merge it. Then the OPAM package could be altered to use it. But the Makefile will always be the primary system.
