### ISSUE TITLE
simple "make"  does not work on bytecode architectures

### ISSUE THREAD

**Issue by treinen** [johnwhitington/camlpdf#32]
Hello,
a simple "make" does not work on bytecode architectures as this invokes unconditionally the target native-code-library, see for instance https://buildd.debian.org/status/fetch.php?pkg=camlpdf&arch=armel&ver=2.3-1&stamp=1573596364&raw=0. Since you wish to provide for exotic architectures (as exprpessed in your reponse to #28), the toplevel Makefile should test
whether native code compilation is available or not.

-Ralf.

**Comment by dbuenzli** [comment]
If that may help  cmdliner's `Makefile` does that, see [here](https://github.com/dbuenzli/cmdliner/blob/db4d02a9eb47b5c43127a67cb121004b03ea3719/Makefile).

**Comment by johnwhitington** [comment]
In this case, you want `make bc`. But I will look into auto-detection.

**Comment by treinen** [comment]
right, "make bc" works for compilation only, but then the target libinstall-byte-code in the OCamlMakefile depends on all ..

**Comment by treinen** [comment]
This patch seems to do the trick:
https://salsa.debian.org/ocaml-team/camlpdf/blob/master/debian/patches/makefile-bytecode

**Comment by johnwhitington** [comment]
Thanks. Fixed here, using your patch and some tidying up:

https://github.com/johnwhitington/camlpdf/commit/3c9bbdb7f3071448e9c33b008f54688fc7e08ec8
