### ISSUE TITLE
Wrong extraction of widths for CID fonts

### ISSUE THREAD

**Issue by alainfrisch** [johnwhitington/camlpdf#33]
This line : https://github.com/johnwhitington/camlpdf/blob/d0aa0397f34551a984e77b37716963db8656f1a4/pdftext.ml#L466

seems suspicious.  It drops explicit width for singleton ranges (for no apparent reason) leading, in one document we have seen, to an empty list of widths for the font.  Removing the special case fixes the issue on our side, and cause no regression otherwise.

Given the comment, the line was introduced for a specific reason (11 years ago...). Do you remember?

**Comment by johnwhitington** [comment]
I think you are right.

This was before CamlPDF was in source control. My guess would be that it was put in to prevent a failure in the ordinary case and was a typo (i.e it should have been `something::read_cid_widths more`).

Please propose your patch...

**Comment by alainfrisch** [comment]
The patch is literally just dropping that line, the general case is ok :-)  I can propose a PR if you want.

**Comment by johnwhitington** [comment]
Yes please!

**Comment by alainfrisch** [comment]
Done (PR#34).
