### ISSUE TITLE
Pdftext.read_font omits Widths in some cases

### ISSUE THREAD

**Issue by Bladtman242** [johnwhitington/camlpdf#36]
Pdftext.read_font does not read the Widths array from modified standard14 fonts, if they to not have a FontDescriptor.

That is: If a standard font has Widths set, but not Fontdescriptor, neither are read.

**Comment by johnwhitington** [comment]
Can you provide an example file?

**Comment by Bladtman242** [comment]
I'm not sure if the document I'm working on is classified, but I'll look into it tomorrow, or make a minimal example from it.
For clarity: The case I'm talking about is not a valid pdf by the specification (It's a standard14 font, with /Widths, /LastChar, and /FirstChar set in the font dictionary, but without a font descriptor, so not supporting it might make sense? I'm just not sure if it's intentional.

**Comment by johnwhitington** [comment]
If adding support for this doesn't impact valid files, which I don't believe it does, then I'm happy to fix it for you, pending the example file.

I am ccing @alainfrisch since he has done some recent work on camlpdf in this area, just in case he has any comments.

**Comment by Bladtman242** [comment]
[komm.pdf](https://github.com/johnwhitington/camlpdf/files/4164353/komm.pdf)
This file is an example (streams decompressed with pdftk).
Object 5 0 is a Standard14 Type1 font with widhts etc. set, but no fontdescriptor.

I'm actually not sure if the best way of handling this is to treat it as a standard font, and ignore the modifications, or to use the modifications, and hope that /MissingWidth won't be needed.

**Comment by johnwhitington** [comment]
Some thoughts:

The ISO standard says this for /FirstChar, /LastChar, /Widths, and /FontDescriptor:

```
For the standard 14 fonts, the entries FirstChar, LastChar, Widths, and 
FontDescriptor shall either all be present or all be absent. Ordinarily, these 
dictionary keys may be absent; specifying them enables a standard font to be 
overridden; see 9.6.2.2, "Standard Type 1 fonts (standard 14 fonts)".

Since this entry was not required for the standard 14 fonts in PDF 1.0 through 
PDF 1.4, for compatibility, PDF readers shall still provide default values for the 
standard 14 fonts when this entry is not present. PDF writers shall include this 
entry for all fonts.
```

So your file is, as you suspect, invalid. Though it may have been valid under some earlier PDF version...

Presently, Pdftext itself does not do any of this -- the StandardFont data item has no space to store these. So what we need to do is extend Pdftext to read what data is available in the case of a StandardFont, and substitute any missing.

So I think we should not special-case this. We should implement the substituion of the standard font data, per the spec, and only consider it "overwritten" when all four entries are present.

This would mean your /Width data would be ignored, and defaults substituted. I'm not sure if this is the job of Pdftext or whatever module uses Pdftext.
