### ISSUE TITLE
The documentation is out of date with the code

### ISSUE THREAD

**Issue by Bladtman242** [johnwhitington/camlpdf#37]
The documentation is out of date with the code.

Case in point: Pdfstandard14.afm_data returns a 4-tuple, not a tripple. Likewise, the textwidth function accepts an additional argument, the encoding, not listed in the html documentation.

**Comment by johnwhitington** [comment]
Here is the current documentation from the pdfstandard14.mli in trunk:

(** The data extracted from the font AFM. This is a 4-tuple, consisting of a
table of header pairs, a table of (character number, width) pairs, a table
of (first, second, kern) triples representing the kerning table and a table
of (character name, width) pairs.  The last table is useful for character which
are identified with a custom encoding and which might not be assigned a number
in the standard encoding. *)

So HTML documentation generated from this should be correct.

What is the URL you are reading the HTML documentation at?

**Comment by Bladtman242** [comment]
[this url](https://www.coherentpdf.com/camlpdf/Pdfstandard14.html).
I assumed it was just a matter of having forgot to rerun the doctool, but maybe I'm wrong.

**Comment by johnwhitington** [comment]
Indeed, it looks like this has not been updated since 2014(!). I have just updated it.

**Comment by Bladtman242** [comment]
Thank you!
