### ISSUE TITLE
0 as initial buffer size leaves null byte

### ISSUE THREAD

**Issue by Bladtman242** [johnwhitington/camlpdf#41]
Calls of the pattern:
```
let out, bytes_ref = Pdfio.input_output_of_bytes b_sz in
Pdfwrite.pdf_to_output false None pdf out;
Pdfio.string_of_bytes !bytes_ref
```

Results in a string that has arbitrary bytes after the %%EOF marker.
The bytes seem to be predominantly NULL bytes in my case, but not exclusively. The first byte is always a linefeed.
The amount of bytes seems to grow with b_sz, but they are present even when b_sz is 0 or 1.

I believe both the arbitrary bytes and the linefeed are illegal.
As I understand it, the last line of a pdf should contain only `%%EOF`, no newline.

Am I doing something wrong in mixin Pdfwrite and Pdfio functions like this?

**Comment by johnwhitington** [comment]
You want `Pdfio.extract_bytes_from_input_output`.

You should not touch bytes_ref manually. In fact, I will look to see if we can make it abstract, to prevent this sort of mistake.

**Comment by Bladtman242** [comment]
Thanks, that does it :)

**Comment by Bladtman242** [comment]
Does this mean the following is also wrong:

```
Pdfread.pdf_of_inout None None
@@ Pdfio.input_of_bytes
@@ Pdfio.bytes_of_caml_bytes bts
```

**Comment by johnwhitington** [comment]
That looks fine (except for the typo -- inout instead of input).

Pdfio has three kinds of i/o.

1. inputs, for input
2. outputs, for output
3. special input-outputs for writing to and then extracting the data from i.e for writing a stream of unknown length to a chunk of memory.

Number (3) is what you needed in your original problem, but you shouldn't need it for much else.

**Comment by Bladtman242** [comment]
Thanks.

For good measure, I should add that giving 0 as the initial buffer size above seems to replace the first byte of the document with a null byte.

**Comment by johnwhitington** [comment]
Thanks. I'll leave this open and look into that.

**Comment by johnwhitington** [comment]
Fixed. When the storage needs to double in size, make sure is at least one byte long:

```
-          let newstream = mkbytes (s.pos * 2) in
+          let newstream = mkbytes (max 1 (s.pos * 2)) in
```

**Comment by Bladtman242** [comment]
Thanks John!
