### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by JuliaLawall** [johnwhitington/camlpdf#42]
Should the Link annotations work with any pdf viewer available for Linux?  My code is as follows.  When using evince, I get a red box and a hand icon when I move into that box, but no link appears.

```
let add_annotations pdf page : Pdfpage.t =
  let border = Pdfannot.make_border 1.0 in
  let color = (1,0,0) in
  let rect = (50.0,50.0,60.0,60.0) in
  let annot = Pdfannot.make ~content:"https://start.ubuntu-mate.org/" ~border:border ~rectangle:rect
      ~colour:color Pdfannot.Link in
  Pdfannot.add_annotation pdf page annot

let do_pages pdf : Pdf.t =
  let pages = Pdfpage.pages_of_pagetree pdf in
  match pages with
    [page] ->
      let newpage = add_annotations pdf page in
      let pdf, pagetree_num = Pdfpage.add_pagetree [newpage] pdf in
      let pdf = Pdfpage.add_root pagetree_num [] pdf in
      Pdf.remove_unreferenced pdf;
      pdf
  | _ -> failwith "only one page expected"

let _ =
  match Array.to_list Sys.argv with
  | [_; in_file; out_file] ->
      begin try
        let ch = open_in_bin in_file in
        let pdf = Pdfread.pdf_of_channel None None ch in
        Pdfwrite.pdf_to_file (do_pages pdf) out_file;
        close_in ch
      with
        err ->
          Printf.printf "Failed to produce output.\n%s\n\n" (Printexc.to_string err);
          exit 1
      end
  | _ ->
      print_string "Syntax: pdfdraft <input> <output>\n\n"; exit 1
```

**Comment by johnwhitington** [comment]
Can you share an output file? I didn't write the code for adding annotations (it was contributed by a Github user), so I would need an example to look at...

**Comment by JuliaLawall** [comment]
On Thu, 4 Mar 2021, John Whitington wrote:

>
> Can you share an output file? I didn't write the code for adding annotations (it was contributed by a Github user), so I would need an example to look at...

res_mar4.pdf is the output file.  test.pdf is the input file that was used
to produce it.

thanks,
julia

**Comment by johnwhitington** [comment]
I can't see any attachments, through Github's web interface or in the email Github sent...

**Comment by JuliaLawall** [comment]
On Fri, 5 Mar 2021, John Whitington wrote:

>
> I can't see any attachments, through Github's web interface or in the email Github sent...

Sorry.  Try downloading
https://who.rocq.inria.fr/Julia.Lawall/test.pdf
https://who.rocq.inria.fr/Julia.Lawall/res_mar4.pdf

thanks,
julia

**Comment by johnwhitington** [comment]
Looks like `content` is not the place for the URL. You will need to build the annotation yourself, since the support for adding annotations is very basic. You will need to add to the `annotrest` part of the `Pdfannot.t` before writing it - maybe modify `Pdfannot.make` to allow an `annotrest`.

Actually, it might be best to ignore the `Pdfannot` module entirely, and just write the annotation manually.

You will need to consult section 12.5 "Annotations" of the PDF manual to learn how to do this. Looks like you need a `/PA` entry with a URI action.

**Comment by JuliaLawall** [comment]
On Sat, 6 Mar 2021, John Whitington wrote:

>
> Looks like content is not the place for the URL. You will need to build the annotation yourself, since the support for adding annotations is very basic. You will need to add to the annotrest part of the Pdfannot.t before writing it - maybe modify
> Pdfannot.make to allow an annotrest.
>
> Actually, it might be best to ignore the Pdfannot module entirely, and just write the annotation manually.
>
> You will need to consult section 12.5 "Annotations" of the PDF manual to learn how to do this. Looks like you need a /PA entry with a URI action.

OK...  I asked on StackOverflow about how to do this and was suggested to
find an existing library, so I was quite happy to find something for
OCaml.  Thanks for the pointer to the manual in any case.

julia
