### ISSUE TITLE
Cannot find file topstart.cmo

### ISSUE THREAD

**Issue by gariac** [johnwhitington/camlpdf#47]
I pulled 2.5.1.
`
File "_none_", line 1:
Error: Cannot find file topstart.cmo
make[1]: *** [OCamlMakefile:966: camlpdf.top] Error 2
make[1]: Leaving directory '/usr/local/src/camlpdf/camlpdf-2.5.1'
make: *** [OCamlMakefile:771: top] Error 2

`
Opensuse 15.3

**Comment by johnwhitington** [comment]
What version of OCaml are you using?
