### ISSUE TITLE
Pdf content stream number with double dash

### ISSUE THREAD

**Issue by mrbech** [johnwhitington/camlpdf#48]
I have run into a PDF which includes the following in the content stream of a page:
`0.00 --7.08 TD`

So a number with two dashes, camlpdf fails to parse this and throws:
```
Pdf.PDFError("Malformed page content")
Raised at Pdfops.lex_next in file "pdfops.ml", line 574, characters 8-53
Called from Pdfops.lex_stream in file "pdfops.ml", line 588, characters 14-38
Called from Pdfops.parse_stream in file "pdfops.ml", line 816, characters 18-44
```
Digging a bit it is the usage of float_of_string and int_of_string in https://github.com/johnwhitington/camlpdf/blob/master/pdfgenlex.ml#L78 that ends up failing.

Looking at the PDF spec this does seem like an invalid PDF, I couldn't find anything that should allow this and real values are defined as:

> A real value shall be written as one or more decimal digits with **an optional sign** and a leading, trailing, or embedded PERIOD (2Eh) (decimal point)

However Chrome, Zathura and Adobe Reader can all read the PDF fine and seems to interpret the value `--7.08` as `-7.08`

I can't share the original PDF but I have recreated the issue in this PDF:
[tiny_test_number_double_dash.pdf](https://github.com/johnwhitington/camlpdf/files/8425539/tiny_test_number_double_dash.pdf)
It has a `--2` in the text:
```
[ (Th) 5 (is) 9 ( ) --2 (is) 9 ( ) -2 (a) 10 ( ) -2 (t) 7 (e)
9 (s) 9 (t) 7 ( ) -2 (P) -1 (D) -1 (F) -1 ( ) 11 (d) 3 (oc) 6 (u) 5 (m) 1
(e) 9 (n) 5 (t) 7 (.) ] TJ
```
If you want I can look into creating a PR with a fix for this.

**Comment by johnwhitington** [comment]
As ever, GhostScript gives the best error message:

```
gorge:Downloads john$ pdf2ps tiny_test_number_double_dash.pdf 
   **** Error: Unknown operator: '--2', processed as number, value: -2
                Output may be incorrect.
```

I will have a look at fixing this today.

**Comment by johnwhitington** [comment]
Ok, I think this does it:

https://github.com/johnwhitington/camlpdf/commit/6535e7b06c7f0326ee9999abdb1d3b75f4ae4248

**Comment by mrbech** [comment]
Seems like that won't work for the case where reals are malformed?

I also tested a bit further, it looks like other readers also accepts any number of dashes (or atleast both 3 and 4 dashes).
[tiny_test_number_triple_dash.pdf](https://github.com/johnwhitington/camlpdf/files/8426197/tiny_test_number_triple_dash.pdf)
Not that I have seen this happen in the wild.

**Comment by mrbech** [comment]
Whipped up this that should do the trick, feel free to use/modify if you want.
```ocaml
let reduce_dash (s : string) =
  let rec inner s =
    match s () with
    | Seq.Cons ('-', s') -> (
        match s' () with Seq.Cons ('-', _) -> inner s' | _ -> s)
    | _ -> s
  in
  String.of_seq (inner (String.to_seq s))

let parse_int s = int_of_string (reduce_dash s)

let parse_float s = float_of_string (reduce_dash s)
```

**Comment by johnwhitington** [comment]
This looks correct, but would be very slow for what is a very low level part of CamlPDF.

I'm going to leave this here, for now, in the absence of any other troublesome files. I think we can assume it's a quirk of a particular PDF generato. In fact, I suspect it only happens for text kerns even with that producer.

**Comment by mrbech** [comment]
I tested your fix with my original PDF I can't share, which has the problem but with real numbers and it still fails.
I have created a test PDF which mimic the issue better having `0 --58.85 TD` in the content stream.
[test_double_dash_real.pdf](https://github.com/johnwhitington/camlpdf/files/8441193/test_double_dash_real.pdf)

**Comment by johnwhitington** [comment]
Thanks. I've fixed it for reals. I'd love to know the source of this strange bug!

**Comment by mrbech** [comment]
Thanks! Indeed a weird one.
So I don't know the origin of the PDF, but its a legal document I can't share.
It contains the meta data `/Producer (Aspose.Pdf for .NET 9.5.0)` but it's unclear if that is really the original producer or if it's just added by whatever platform/tool someone may have used to store/manipulate the PDF with.
The problem only happens on a few pages of the document and it looks like it could be multiple PDFs merged into one.

**Comment by johnwhitington** [comment]
Thanks. By the way, can you share what you’re using CamlPDF for? Not many people use it directly (rather than through a tool which depends on it) so I am always interested to know…
