### ISSUE TITLE
Release for OCaml 5.0 support

### ISSUE THREAD

**Issue by kit-ty-kate** [johnwhitington/camlpdf#49]
Hi,

I can see that `master` is compatible with OCaml 5.0 but the latest release is not.
Would it be possible to get a new release? I can do the release on opam-repository if that can help but i need a tag to hold on to.

**Comment by johnwhitington** [comment]
Yes, but the tip of `master` is not suitable, because I've been making big changes recently. I'll find a suitable place in the history to put a tag this weekend, and update this bug when I've done so.

**Comment by johnwhitington** [comment]
Ok, you can use tag v2.5.3 which is in fact tip of master.

I have tested that the OPAM package `graphicspdf` still compiles. `bytepdf`, which is the only third-party package using camlpdf already has a version restraint on it.

There will be a new cpdf at some point, which will support OCaml 5, but I'm deep into rewriting cpdf's text and font support to support TrueType embedding, and it's not stable enough to release easily yet. If I can't release it easily by the time OCaml 5 is released, I'll provide a version which just has the OCaml 5 changes.

**Comment by johnwhitington** [comment]
v2.6 is on the way soonish, so I am closing this.
