### ISSUE TITLE
Compilation fails with OCaml 5

### ISSUE THREAD

**Issue by klartext** [johnwhitington/camlpdf#59]
In OCaml 5, the Genlex module has been removed:
https://v2.ocaml.org/releases/5.0/notes/Changes

**Comment by klartext** [comment]
https://discuss.ocaml.org/t/module-stream-removed-from-5-0-standard-library/10218/2

**Comment by johnwhitington** [comment]
Per https://github.com/johnwhitington/camlpdf/issues/49 you should be able to use tag v2.5.3 for OCaml 5
