### ISSUE TITLE
Why simple fonts does not load widths

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [johnwhitington/camlpdf#61]
I am trying to get to the character widths for a SimpleFont.

Looking at the code here: https://github.com/johnwhitington/camlpdf/blob/master/pdftext.ml#L432
When loading a simple font, `firstchar`, `lastchar` and `widths` are all initilized to 0 (or empty list).

What is the reason for that?
What is the point of having the `firstchar`, `lastchar` and `widths` members of the simple font if they are not read anyway?

**Comment by johnwhitington** [comment]
It looks like the widths can be read directly from the fontmetrics entry.

The firstchar, lastchar and widths entries are used when writing a font.

This part of the code was written about fifteen years ago, and I couldn't tell you why now.

**Comment by RudolfVonKrugstein** [comment]
Ah, ok, fair enough :).

Thank you for the information and thank you for camlpdf!
