### ISSUE TITLE
Example-wish: adding href's

### ISSUE THREAD

**Issue by klartext** [johnwhitington/camlpdf#8]
Hello,
a wish for an example: a tool that looks for href-strings ( "http://[^ \t\r\n]+" )
and creates clickable href's from that (so: letting the text unchanged, but add a clickable url).
This would be good for pdf-files, which where created from ps-files via ps2pdf, for example.
Any http-stuff could be changed to be a clickable href then.

**Comment by johnwhitington** [comment]
This is a job for a higher-level program. Camlpdf is a simple library. You might suggest it for cpdf.
